------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">✍ EJERCICIOS NUMPY PARA @EGGERS</h3><br>
------------------------------------------------------------------------------------------------------<br>

1. Crea un vector entre 7 y 66.
2. Invierte el vector generado anteriormente.
3. Matriz de 4x4 con valores entre 0 y 15.
5. Crea la matriz identidad de 5x5.
6. Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.
7. Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.
8. Crea un array de ceros de 2x7.
9. Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.
10. Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.

In [133]:
import numpy as np

In [134]:
v = np.array([7,66])
v

array([ 7, 66])

In [164]:
v_invert = np.flip(v)
v_invert

array([66,  7])

In [165]:
m44 = np.matrix([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
m44

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [137]:
id55= np.identity(5).astype(int)
id55

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [138]:
m = np.zeros((5, 5)).astype(int)
m[2,2]=1
m[0]=1
m[-1]=1
m[:,0]=1
m[:,-1]=1
m

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [168]:
array= np.arange(0,4,dtype=int)
mat= np.identity(4).astype(int)
mat[0]=mat[1]=mat[2]=mat[3]= array
mat

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [140]:
m0 = np.zeros((2, 7)).astype(int)
m0

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [141]:
m0 = np.zeros((5, 4)).astype(int)
m0[0]=1
m0

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [163]:
#Creamos la función que analiza si la posicion es par o impar, con el resto de la division.
def fn(x, y):
    return((x + y) % 2)

#Utilizando una funcion de numpy ya existente, nos aprovechamos para crear la matriz del tablero de ajedrez.
ajedrez = np.fromfunction(fn, (8, 8), dtype='int')

print(ajedrez)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
